### ISSUE TITLE
Criar/validar diagramas de sequência 

### ISSUE THREAD

**Issue by rcmgleite** [rcmgleite/labSoft2_Estoque#2]
- [ ] Consumir
- [ ] Atualizar

**Comment by rcmgleite** [comment]
Consumir:
![lab_eng_soft2_sequence - consumir](https://cloud.githubusercontent.com/assets/5962389/6607814/8bba4442-c820-11e4-828c-3f7619353229.png)

**Comment by rcmgleite** [comment]
atualizar:
![lab_eng_soft2_sequence - atualizar](https://cloud.githubusercontent.com/assets/5962389/6607850/dbc31f36-c820-11e4-8e15-1a18ae628cab.png)

**Comment by soriani** [comment]
Precisa colocar as classes fronteiras e classes controles
